export const getDate1= "getDate"
export const getMonth1= "getMonth"
export const getYear1= "getYear"
export const getFirstName1= "getFirstName"
export const getSurName1= "getSurName"
export const getPhoneNumber1= "getPhoneNumber"
export const getPassword1= "getPassword"
export const getGender1= "getGender"